[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true

# Add other black configurations if needed.
[tool.black]
line-length = 120

[project]
name = "hurst-exponent"
dynamic = ["version"]

[tool.poetry]
name = "hurst-exponent"
version = "0.0.0"
description = "Hurst exponent estimator"
authors = ["Anastasia Bugeenko <anabugaenko@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/anabugaenko/hurst_exponent"
repository = "https://github.com/anabugaenko/hurst_exponent"
keywords = ["hurst", "autocorrelation", "time-series", "fractals"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Intended Audience :: Science/Research"
]

[tool.poetry.dependencies]
python = "^3.9"
scipy = "*"
numpy = "*"
pandas = "*"
pandas-stubs = "*"
typing = "*"
statsmodels = "*"
stochastic = "*"
matplotlib = "*"
powerlaw_function = { git = "https://github.com/anabugaenko/powerlaw-function" }

[tool.poetry.dev-dependencies]
pylint = "^2.17.5"
mypy = "^1.5.1"
pre-commit = "^3.4.0"
pytest = "^7.4.1"
pytest-mock = "^3.11.1"
pytest-xdist = "^3.3.1"
black = "*"
flake8 = "*"

[build]
include = ["README.md"]
